version: 2
jobs:
  build:
    docker:
      - image: cimg/php:7.4

    steps:
      - checkout

      # Install pcov extension for code coverage.
      - run: sudo pecl install pcov

      # Install Composer dependencies.
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # Download CodeClimate test reporting tool.
      - run:
          name: Set up CodeClimate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      # Run the build.
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            composer dev:lint:syntax
            composer dev:lint:style
            composer dev:analyze:phpstan
            composer dev:analyze:psalm
            composer dev:test:coverage:ci
            ./cc-test-reporter format-coverage --input-type clover build/coverage/clover.xml
            ./cc-test-reporter upload-coverage
